# Generated by Django 6.0.3 on 2026-03-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True, verbose_name='Slug URL')),
                ('extrait', models.TextField(max_length=400, verbose_name='Extrait / chapô')),
                ('contenu', models.TextField(verbose_name='Contenu complet')),
                ('categorie', models.CharField(choices=[('assemblee', 'Assemblée Nationale'), ('circonscription', 'En Circonscription'), ('presse', 'Revue de Presse'), ('video', 'Vidéo')], default='assemblee', max_length=30, verbose_name='Catégorie')),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualites/', verbose_name='Image principale')),
                ('date_publication', models.DateField(verbose_name='Date de publication')),
                ('en_vedette', models.BooleanField(default=False, verbose_name='Article en vedette (featured)')),
                ('publie', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('sujet', models.CharField(choices=[('demande', "Demande d'information"), ('suggestion', 'Suggestion / Proposition'), ('permanence', 'Demande de permanence'), ('partenariat', 'Partenariat'), ('autre', 'Autre')], default='demande', max_length=30, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('lu', models.BooleanField(default=False, verbose_name='Message lu')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
            ],
            options={
                'verbose_name': 'Message de Contact',
                'verbose_name_plural': 'Messages de Contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterAbonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse e-mail')),
                ('actif', models.BooleanField(default=True, verbose_name='Abonnement actif')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
            ],
            options={
                'verbose_name': 'Abonné Newsletter',
                'verbose_name_plural': 'Abonnés Newsletter',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
