# Generated by Django 6.0.3 on 2026-03-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='categorie',
            field=models.CharField(choices=[('assemblee', 'Assemblée Nationale'), ('circonscription', 'En Circonscription'), ('agriculture', 'Agriculture'), ('economie', 'Économie'), ('education', 'Éducation'), ('sante', 'Santé'), ('environnement', 'Environnement'), ('infrastructure', 'Infrastructure'), ('jeunesse', 'Jeunesse'), ('culture', 'Culture'), ('social', 'Social'), ('securite', 'Sécurité'), ('presse', 'Revue de Presse'), ('video', 'Vidéo')], default='assemblee', max_length=30, verbose_name='Catégorie'),
        ),
    ]
