# Generated by Django 6.0.3 on 2026-03-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_actualite_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(default='🏛️', max_length=10)),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('type', models.CharField(choices=[('principale', 'Principale'), ('membre', 'Membre')], default='membre', max_length=20)),
                ('description', models.TextField(verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(default='🏙️', max_length=10)),
                ('nom', models.CharField(max_length=100)),
                ('type_commune', models.CharField(default='Sous-Préfecture', max_length=100, verbose_name='Type')),
                ('population', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True, verbose_name='Description courte')),
                ('projets', models.TextField(blank=True, verbose_name='Projets (1 par ligne)')),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='EvenementAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('assemblee', 'Assemblée Nationale'), ('circonscription', 'En Circonscription'), ('public', 'Événement Public'), ('autre', 'Autre')], default='assemblee', max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('heure', models.CharField(blank=True, max_length=60)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('avenir', 'À venir'), ('realise', 'Tenu'), ('annule', 'Annulé')], default='avenir', max_length=20)),
                ('en_avant', models.BooleanField(default=False, verbose_name='Mettre en avant')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements Agenda',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('contexte', models.CharField(max_length=100, verbose_name='Contexte (ex: Séance plénière)')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tag', models.CharField(max_length=60, verbose_name='Étiquette')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Permanence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('titre', models.CharField(max_length=200)),
                ('lieu', models.CharField(max_length=200)),
                ('heure', models.CharField(max_length=60, verbose_name='Horaire')),
                ('passee', models.BooleanField(default=False, verbose_name='Passée')),
            ],
            options={
                'verbose_name': 'Permanence',
                'verbose_name_plural': 'Permanences',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TexteLoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(default='📜', max_length=10)),
                ('type', models.CharField(choices=[('amendement', 'Amendement'), ('question_ecrite', 'Question écrite'), ('question_orale', 'Question orale'), ('resolution', 'Proposition de résolution')], max_length=30)),
                ('titre', models.CharField(max_length=255)),
                ('meta', models.CharField(max_length=255, verbose_name='Date & statut')),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Texte / Proposition',
                'verbose_name_plural': 'Textes & Propositions',
                'ordering': ['ordre'],
            },
        ),
    ]
