# Generated by Django 6.0.3 on 2026-03-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_commission_commune_evenementagenda_intervention_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenementagenda',
            name='heure',
        ),
        migrations.RemoveField(
            model_name='permanence',
            name='heure',
        ),
        migrations.AddField(
            model_name='evenementagenda',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de début'),
        ),
        migrations.AddField(
            model_name='evenementagenda',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de fin'),
        ),
        migrations.AddField(
            model_name='permanence',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de début'),
        ),
        migrations.AddField(
            model_name='permanence',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de fin'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='categorie',
            field=models.CharField(choices=[('assemblee', 'Assemblée Nationale'), ('circonscription', 'En Circonscription'), ('agriculture', 'Agriculture'), ('economie', 'Économie'), ('education', 'Éducation'), ('sante', 'Santé'), ('environnement', 'Environnement'), ('infrastructure', 'Infrastructure'), ('jeunesse', 'Jeunesse'), ('culture', 'Culture'), ('social', 'Social'), ('securite', 'Sécurité'), ('presse', 'Revue de Presse'), ('video', 'Vidéo')], default='assemblee', max_length=30),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='contenu',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='en_vedette',
            field=models.BooleanField(default=False, verbose_name='En vedette'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='extrait',
            field=models.TextField(max_length=400, verbose_name='Extrait'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actualites/'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='slug',
            field=models.SlugField(blank=True, max_length=270, unique=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='icone',
            field=models.CharField(default='🏛️', max_length=10, verbose_name='Emoji'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='ordre',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='icone',
            field=models.CharField(default='🏙️', max_length=10, verbose_name='Emoji'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='ordre',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='population',
            field=models.CharField(blank=True, max_length=60, verbose_name='Population'),
        ),
        migrations.AlterField(
            model_name='evenementagenda',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='evenementagenda',
            name='lieu',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='evenementagenda',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='date_envoi',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='lu',
            field=models.BooleanField(default=False, verbose_name='Lu'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='sujet',
            field=models.CharField(choices=[('demande', "Demande d'information"), ('suggestion', 'Suggestion / Proposition'), ('permanence', 'Demande de permanence'), ('partenariat', 'Partenariat'), ('autre', 'Autre')], default='demande', max_length=30),
        ),
        migrations.AlterField(
            model_name='newsletterabonne',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='newsletterabonne',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsletterabonne',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='permanence',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='permanence',
            name='lieu',
            field=models.CharField(max_length=200, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='permanence',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='texteloi',
            name='icone',
            field=models.CharField(default='📜', max_length=10, verbose_name='Emoji'),
        ),
        migrations.AlterField(
            model_name='texteloi',
            name='ordre',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='texteloi',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='texteloi',
            name='type',
            field=models.CharField(choices=[('amendement', 'Amendement'), ('question_ecrite', 'Question écrite'), ('question_orale', 'Question orale'), ('resolution', 'Proposition de résolution')], max_length=30, verbose_name='Type'),
        ),
    ]
