# Generated by Django 6.0.3 on 2026-04-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_evenementagenda_heure_remove_permanence_heure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text="Copiez l'URL complète du post (clic droit sur la date du post → Copier l'adresse du lien)", max_length=500, verbose_name='URL du post Facebook')),
                ('legende', models.CharField(blank=True, help_text="Courte description affichée si l'embed ne charge pas", max_length=200, verbose_name='Légende (optionnelle)')),
                ('actif', models.BooleanField(default=True, verbose_name='Afficher sur le site')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Publication Facebook',
                'verbose_name_plural': 'Publications Facebook',
                'ordering': ['ordre', '-created_at'],
            },
        ),
    ]
