# Generated by Django 6.0.3 on 2026-04-19 11:43
# Corrigé pour MySQL :
#   - RunSQL TRUNCATE en premier : vide les anciens enregistrements sans fb_id
#     (évite IntegrityError sur unique=True avec default='')
#   - date_post default='2026-01-01 00:00:00' (string ISO) au lieu de default=1
#   - AlterField created_at supprimé (auto_now_add crash MySQL sur table existante)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_facebookpost'),
    ]

    operations = [

        # ── Vider les anciens enregistrements ─────────────────────────────────
        # Les posts de l'ancien modèle (sans fb_id) sont inutilisables.
        # La commande sync_facebook les recréera proprement depuis l'API.
        migrations.RunSQL(
            sql="TRUNCATE TABLE website_facebookpost;",
            reverse_sql=migrations.RunSQL.noop,
        ),

        # ── Options ──────────────────────────────────────────────────────────
        migrations.AlterModelOptions(
            name='facebookpost',
            options={
                'ordering': ['-date_post'],
                'verbose_name': 'Publication Facebook',
                'verbose_name_plural': 'Publications Facebook',
            },
        ),

        # ── Nouveaux champs ───────────────────────────────────────────────────
        migrations.AddField(
            model_name='facebookpost',
            name='fb_id',
            field=models.CharField(
                default='',
                max_length=100,
                unique=True,
                verbose_name='ID Facebook',
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='facebookpost',
            name='date_post',
            field=models.DateTimeField(
                default='2026-01-01 00:00:00',
                verbose_name='Date de publication',
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='facebookpost',
            name='image_url',
            field=models.URLField(
                blank=True,
                null=True,
                max_length=500,
                verbose_name='URL Image',
            ),
        ),

        # ── Champs modifiés ───────────────────────────────────────────────────
        migrations.AlterField(
            model_name='facebookpost',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Afficher'),
        ),

        migrations.AlterField(
            model_name='facebookpost',
            name='legende',
            field=models.TextField(blank=True, verbose_name='Texte du post'),
        ),

        migrations.AlterField(
            model_name='facebookpost',
            name='ordre',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),

        migrations.AlterField(
            model_name='facebookpost',
            name='url',
            field=models.URLField(max_length=500, verbose_name='URL du post'),
        ),
    ]