# Generated by Django 6.0.3 on 2026-04-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_facebookpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookpost',
            options={'ordering': ['-date_post'], 'verbose_name': 'Publication Facebook', 'verbose_name_plural': 'Publications Facebook'},
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='date_post',
            field=models.DateTimeField(default=1, verbose_name='Date de publication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='fb_id',
            field=models.CharField(default='qwew', max_length=100, unique=True, verbose_name='ID Facebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Image'),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Afficher'),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='legende',
            field=models.TextField(blank=True, verbose_name='Texte du post'),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='ordre',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='url',
            field=models.URLField(max_length=500, verbose_name='URL du post'),
        ),
    ]
