# Generated by Django 6.0.3 on 2026-04-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_facebookpost_options_facebookpost_date_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpost',
            name='image_url',
            field=models.TextField(blank=True, null=True, verbose_name='URL Image'),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='url',
            field=models.URLField(max_length=1000, verbose_name='URL du post'),
        ),
    ]
