# Generated by Django 6.0.3 on 2026-04-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_facebookpost_image_url_alter_facebookpost_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetFondation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(default='🌱', max_length=10, verbose_name='Emoji')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du projet')),
                ('description', models.TextField(verbose_name='Description')),
                ('domaine', models.CharField(choices=[('education', 'Éducation'), ('jeunesse', 'Insertion des Jeunes'), ('communaute', 'Développement Communautaire'), ('sante', 'Santé'), ('autre', 'Autre')], default='education', max_length=20, verbose_name='Domaine')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('realise', 'Réalisé')], default='planifie', max_length=20, verbose_name='Statut')),
                ('beneficiaires', models.CharField(blank=True, max_length=150, verbose_name='Bénéficiaires visés')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='Lieu / Zone')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fondation/', verbose_name='Image')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Projet — Fondation Rêvons Grand',
                'verbose_name_plural': 'Projets — Fondation Rêvons Grand',
                'ordering': ['ordre', 'titre'],
            },
        ),
    ]
